### ISSUE TITLE
Ignore shortcut

### ISSUE THREAD

**Issue by bladnman** [joeyjiron06/intellij-auto-align#1]
I have found an issue in a STYLUS file where an indentation is destructive:

`support-for-ie ?= false`

becomes

`support-for-ie ?          = false`

And this no longer works.

**Comment by joeyjiron06** [comment]
ok thanks. i will look into it

**Comment by joeyjiron06** [comment]
fixed with [this](https://github.com/joeyjiron06/intellij-auto-align/commit/2343ff242178037aebd148230a16835b5959d4f1) commit!

**Comment by bladnman** [comment]
Heck yeah! Awesome!
