### ISSUE TITLE
Reformatting break C++ code

### ISSUE THREAD

**Issue by GauthierPLM** [joeyjiron06/intellij-auto-align#9]
Reformatting C++ code create invalid code, because of "::" operator (used to indicate parent of a function/variable). The plugin should detect the file type and don't reformat on "::" in C++ files.

Original code:
![correct-code](https://cloud.githubusercontent.com/assets/2579741/14761462/d193f65a-0962-11e6-9fb2-a4405b4bc7d6.png)

Reformated code:
![reformated-code](https://cloud.githubusercontent.com/assets/2579741/14761463/d19654a4-0962-11e6-8baf-c9c4969759d5.png)

**Comment by joeyjiron06** [comment]
HI Kendos, good catch and thanks for filing this issue. Another edge case to figure out, shouldnt be hard to fix. Working on it today and will hopefully put out a fix either later today or tomorrow.

**Comment by joeyjiron06** [comment]
just pushed out a release with the fix. please let me know if it works as expected.

**Comment by GauthierPLM** [comment]
Yep it works well ! Just have a question : is it normal that the align is for the entire file and not local to the function ? Sometimes it looks strange when there is only a variable asignement in the function, and it is aligned with another 20 lines above.

**Comment by joeyjiron06** [comment]
sweet closing this issue!
yup thats normal as of now. i would like to get to the project to a place where i can be smart about auto aligning based on scopes. it's just a matter of learning the jetbrains api a little better. The way i usually handle aligning just a function is by highlighting the whole function  then using auto-aligner.
